# Generated by Django 5.1.2 on 2024-10-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='category_name',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
