# Generated by Django 5.1.2 on 2024-10-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assign_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
